### ISSUE TITLE
rest.address must be set

### ISSUE THREAD

**Issue by likaiqing** [ververica/flink-sql-gateway#7]
hi,I run CreateTableOperationTest.java with my insert code in test source,but occur exception，Looking forward to your reply
below is my code and exception

code:
public class CreateTableOperationTest extends OperationTestBase {

	@Test
	public void testCreateTable() {

		final String ddlTemplate = "create table %s(\n" +
			"  a int,\n" +
			"  b bigint,\n" +
			"  c varchar\n" +
			") with (\n" +
			"  'connector.type'='filesystem',\n" +
			"  'format.type'='csv',\n" +
			"  'connector.path'='file:///tmp/MyTable1'\n" +
			")\n";
		CreateTableOperation operation = new CreateTableOperation(context, String.format(ddlTemplate, "MyTable1"));
		ResultSet resultSet = operation.execute();
		assertEquals(OperationUtil.AFFECTED_ROW_COUNT0, resultSet);

		String[] tables = context.getExecutionContext().getTableEnvironment().listTables();
		assertArrayEquals(new String[] { "MyTable1" }, tables);
		InsertOperation insertOperation = new InsertOperation(context, "INSERT INTO MyTable1 select 1,1,'test'");
		ResultSet execute = insertOperation.execute();
		System.out.println(execute);

	}
}

Exception:

java.lang.RuntimeException: Error running SQL job.

	at com.ververica.flink.table.gateway.operation.InsertOperation.executeUpdateInternal(InsertOperation.java:201)
	at com.ververica.flink.table.gateway.operation.InsertOperation.execute(InsertOperation.java:84)
	at com.ververica.flink.table.gateway.operation.CreateTableOperationTest.testCreateTable(CreateTableOperationTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: Could not execute program.
	at com.ververica.flink.table.gateway.ProgramDeployer.deploy(ProgramDeployer.java:83)
	at com.ververica.flink.table.gateway.operation.InsertOperation.executeUpdateInternal(InsertOperation.java:198)
	... 25 more
Caused by: java.lang.RuntimeException: Couldn't retrieve standalone cluster
	at org.apache.flink.client.deployment.StandaloneClusterDescriptor.lambda$retrieve$0(StandaloneClusterDescriptor.java:53)
	at org.apache.flink.client.deployment.executors.AbstractSessionClusterExecutor.execute(AbstractSessionClusterExecutor.java:64)
	at com.ververica.flink.table.gateway.ProgramDeployer.deploy(ProgramDeployer.java:81)
	... 26 more
Caused by: java.lang.NullPointerException: rest.address must be set
	at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:104)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.getWebMonitorAddress(HighAvailabilityServicesUtils.java:196)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createClientHAService(HighAvailabilityServicesUtils.java:146)
	at org.apache.flink.client.program.rest.RestClusterClient.<init>(RestClusterClient.java:161)
	at org.apache.flink.client.deployment.StandaloneClusterDescriptor.lambda$retrieve$0(StandaloneClusterDescriptor.java:51)
	... 28 more

**Comment by godfreyhe** [comment]
hi @likaiqing, the context defined in OperationTestBase is only used for test, can not connect the flink cluster.
If want to run above test, you can do as the following steps:
1. startup a flink cluster
2. add the `FLINK_CONF_DIR=<your cluster conf dir>` to the environment variables
3. override `getDefaultContext` method, create a DefaultContext using `public DefaultContext(Environment defaultEnv, List<URL> dependencies)` constructor

I will improve this later
