### ISSUE TITLE
When run e2e test met the error "Could not create execution context"

### ISSUE THREAD

**Issue by JaneGuoS** [ververica/flink-sql-gateway#99]
When run the test with the command " FLINK_HOME=/mnt/c/gjy/software/flink-1.11.6 SQL_GATEWAY_HOME=/mnt/c/gjy/software/flink-sql-gateway-flink-1.11.1/build-target ./run-tests.sh", 

met the error
Request to http://localhost:8083/v1/sessions returns an error.
Request Method: POST
Request Body: {
    "planner": "blink",
    "execution_type": "batch"
}
Internal server error.
<Exception on server side:
com.ververica.flink.table.gateway.utils.SqlExecutionException: Could not create execution context.
        at com.ververica.flink.table.gateway.context.ExecutionContext$Builder.build(ExecutionContext.java:713)
        at com.ververica.flink.table.gateway.context.SessionContext.<init>(SessionContext.java:47)
        at com.ververica.flink.table.gateway.rest.session.SessionManager.createSession(SessionManager.java:119)
        at com.ververica.flink.table.gateway.rest.handler.SessionCreateHandler.handleRequest(SessionCreateHandler.java:100)

Use the default configuration sql-gateway-defaults.yaml and e2e-tests/data/test-config.yaml, neither works

**Comment by smm321** [comment]
It seems that something wrong when SessionContext init ExecutionContext. Have you set flink lib dir?
